// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBonOrDP6LR4Re9OglYB7JOOaXX43bPaCs',
    appId: '1:795673718463:web:2b721361bcfacb45f4a00a',
    messagingSenderId: '795673718463',
    projectId: 'roomiapp-2482a',
    authDomain: 'roomiapp-2482a.firebaseapp.com',
    storageBucket: 'roomiapp-2482a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEt29FHs5r8zpDhDt08fX4EZt4rzz5Y4I',
    appId: '1:795673718463:android:e2c0e1a22da29300f4a00a',
    messagingSenderId: '795673718463',
    projectId: 'roomiapp-2482a',
    storageBucket: 'roomiapp-2482a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-nwZroD2Zg5SJSZMZN_KZXepszJtDGIg',
    appId: '1:795673718463:ios:5a0527dcc65f404ff4a00a',
    messagingSenderId: '795673718463',
    projectId: 'roomiapp-2482a',
    storageBucket: 'roomiapp-2482a.firebasestorage.app',
    iosBundleId: 'com.example.roomi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-nwZroD2Zg5SJSZMZN_KZXepszJtDGIg',
    appId: '1:795673718463:ios:5a0527dcc65f404ff4a00a',
    messagingSenderId: '795673718463',
    projectId: 'roomiapp-2482a',
    storageBucket: 'roomiapp-2482a.firebasestorage.app',
    iosBundleId: 'com.example.roomi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBonOrDP6LR4Re9OglYB7JOOaXX43bPaCs',
    appId: '1:795673718463:web:f98131849777aee3f4a00a',
    messagingSenderId: '795673718463',
    projectId: 'roomiapp-2482a',
    authDomain: 'roomiapp-2482a.firebaseapp.com',
    storageBucket: 'roomiapp-2482a.firebasestorage.app',
  );
}
